import Head from "next/head";
import { useState } from "react";

export default function Home() {
	const [liste, setListe] = useState<String[]>([]);

	const [name, setName] = useState("");
	const handleSubmit = (e: any) => {
		e.preventDefault();
		setListe([...liste, name]);
	}
	const handleDeletion = (i: number) => {
		liste.splice(i, 1);
		setListe([...liste])
	}
	const Spinner = () => {
		return (
			<div className="border-4 m-2 duration-100 rounded-full p-4 border-t-red-500 border-gray-800 animate-spin"></div>
		)

	}
	return (

		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className=" flex min-h-screen flex-col items-center justify-center bg-gray-900">

				<Spinner />
				<form action="" onSubmit={
					(e) => handleSubmit(e)
				}>
					<input type="text " onChange={(e) => setName(e.target.value)} className="rounded " />
					<button type="submit" className=" p-1.5 m-2 bg-red-500 hover:bg-red-800 transition-colors duration-300 rounded">
						Envoyer
					</button>
				</form>

				<div className="flex flex-col space-y-4">

					{liste.map(
						(li, index) => (
							<div key={index} className="text-white flex gap-4">
								{li}
								<button onClick={
									() => handleDeletion(index)
								} className="bg-red-500 rounded-md hover:bg-red-700 duration-100 transition-all font-extrabold">Supprimer</button>
							</div>
						))}
				</div>


			</main>

		</>
	);
}
